### ISSUE TITLE
Optimize Python DataFrame reads for Demo

### ISSUE THREAD

**Issue by zavoraad** [databricks-industry-solutions/hls-payer-mrf-sparkstreaming#11]
instead of json.loads() inside of an RDD is there a faster approach.

https://github.com/databricks-industry-solutions/hls-payer-mrf-sparkstreaming/blob/main/01_payer_mrf_demo.py#L61-L69

**Comment by dbbnicole** [comment]
This PR includes some optimization about that particular step: https://github.com/databricks-industry-solutions/hls-payer-mrf-sparkstreaming/pull/13

**Comment by zavoraad** [comment]
Nice, flatMap should be much quicker. 

Also, great find on the widgets.txt() for interactive values. That is a much better approach

**Comment by zavoraad** [comment]
This would avoid the call to rdd and/or flatMap correct? 

I can take a look at updating functionality here to provide an array<String> instead. Let me create a new branch for this. https://github.com/databricks-industry-solutions/hls-payer-mrf-sparkstreaming/blob/main/src/main/scala/com/databricks/JsonChunks.scala#L54-L58

**Comment by zavoraad** [comment]
@balbarka  spark.read.json requires an RDD as input, so we'd still need to convert. Is there much (if any) savings if we still need to convert to an RDD anyway?

**Comment by balbarka** [comment]
The benefits I see are keeping rdds out of transforms after write to delta
is that any inspection of the json_payload will require the split every
time it's inspected, thus it is best to do before write write to delta. I
don't think the split will be impacted by schema version, thus I don't
think moving the split into the custom format will complicate schema
evolution (which I think we want to manage in downstream applications and
leave out of the custom )

**Comment by zavoraad** [comment]
#22
