### ISSUE TITLE
Change json_payload format from STRING to ARRAY<STRING>

### ISSUE THREAD

**Issue by balbarka** [databricks-industry-solutions/hls-payer-mrf-sparkstreaming#15]
Since the payload column will have to be split into array for all data sources and won't change between schema versions, it is better to move the split logic into the custom MRF source. In the interim, v0.3.0 can be transformed into the expected future format with the following:

```python
from pyspark.sql.functions import col, lit, when, regexp_replace, split, substring
from pyspark.sql.column import Column

def in_network_string_to_array(json_payload: Column):
    jp1 = regexp_replace(json_payload, "^\[", "")
    jp2 = regexp_replace(jp1, "]$", "")
    jp3 = split(regexp_replace(jp2, "\}\,\s*\\{\"negotiation_arrangement\":", "\}" + chr(1)+ "\\{\"negotiation_arrangement\":"), chr(1))
    return jp3
    
def provider_groups_string_to_array(json_payload: Column):
    jp1 = regexp_replace(json_payload, "^\[", "")
    jp2 = regexp_replace(jp1, "]$", "")
    jp3 = split(regexp_replace(jp2, "\}\,\s*\\{\"provider_groups\":", "\}" + chr(1)+ "\\{\"negotiation_arrangement\":"), chr(1))
    return jp3

def head_string_to_array(json_payload: Column):
    jp1 = regexp_replace(json_payload, "^\[", "")
    jp2 = regexp_replace(jp1, "]$", "")
    return F.array(json_payload,)

def string_to_array(header_key:Column, json_payload: Column):
    return when(header_key == lit('in_network'), in_network_string_to_array(json_payload)).otherwise(
           when(header_key == lit('provider_references'), provider_groups_string_to_array(json_payload)).otherwise(
           when(header_key == lit(''), head_string_to_array(json_payload))))

new_format = spark.table('main.pt_stage.inr_existing_format') \
                                  .withColumn("json_payload", string_to_array(col('header_key'), col('json_payload'))).collect()
```

**Comment by zavoraad** [comment]
@balbarka  Leaving off here today... I was hoping to find an elegant solution to map the Array[Byte] to Array[String]. 

Was hoping to combine something like foldleft() and [arrayHasNext()](https://github.com/databricks-industry-solutions/hls-payer-mrf-sparkstreaming/blob/main/src/main/scala/com/databricks/ByteParser.scala#L70)

https://github.com/databricks-industry-solutions/hls-payer-mrf-sparkstreaming/blob/feature-json-as-array/src/main/scala/com/databricks/JsonChunks.scala#L65

**Comment by zavoraad** [comment]
@balbarka I have updated the code to support payload as an array of strings. The jar is attached in 0.3.3v draft release.  can you confirm this works for your needs? Curious if you get faster performance off of parsing this column as well.

https://github.com/databricks-industry-solutions/hls-payer-mrf-sparkstreaming/releases/tag/untagged-729f09cc62137405e710

**Comment by balbarka** [comment]
option works as expected, but returns empty arrays on test file:
wget -O /dbfs/user/hive/warehouse/hls_dev_payer_transparency.db/raw_files/2022-12-01_UMR--Inc-_Third-Party-Administrator_ENCORE-ENTERPRISES-AIRROSTI-DCI_TX-DALLAS-NON-EVALUATED-GAP_-ENC_NXBJ_in-network-rates.json.gz  https://uhc-tic-mrf.azureedge.net/public-mrf/2022-12-01/2022-12-01_UMR--Inc-_Third-Party-Administrator_ENCORE-ENTERPRISES-AIRROSTI-DCI_TX-DALLAS-NON-EVALUATED-GAP_-ENC_NXBJ_in-network-rates.json.gz

**Comment by balbarka** [comment]
Validated .option("payloadAsArray", "true") now works on v3.0 using https://uhc-tic-mrf.azureedge.net/public-mrf/2022-12-01/2022-12-01_UMR--Inc-_Third-Party-Administrator_ENCORE-ENTERPRISES-AIRROSTI-DCI_TX-DALLAS-NON-EVALUATED-GAP_-ENC_NXBJ_in-network-rates.json.gz
