### ISSUE TITLE
Multiple file parsing in a distributed manner (mapPartitions)

### ISSUE THREAD

**Issue by zavoraad** [databricks-industry-solutions/hls-payer-mrf-sparkstreaming#4]
stream multiple files to different output locations

**Comment by zavoraad** [comment]
What is the optimal way to run this code on a directory of files? The readStream.load() command expects one JSON file in cloud storage. 

Naively, is it possible to run something like 
df = sc.parallelize(dbutils.fs.ls("list my directory of json files"))
df.rdd.map(lambda x: 
  readStream(x)
  query = ( writestream(x)  ) 
  query.awaitFinish
  )

**Comment by dbbnicole** [comment]
The UDF step in readStream won't have access to the spark session for `spark.read`. But there are stuff like unzipping that can be parallelized in this fashion.

**Comment by zavoraad** [comment]
Good call on the spark session. Then the non-spark session way of running that would be...

def runStream(file):
  readStream(x)
  query = writeStream(...)
  awaitFinish()

streamJobs = dbutils.fs.ls("list my directory of json files")

map(runStream(), streamjobs)

**Comment by zavoraad** [comment]
@balbarka  let me know if you're comfortable with the above approach. I think that is reasonable, and maybe providing a general rule of thumb on how to size a cluster for this is what we are missing.

initially thinking 2 executors, 2 cores each, per file and at least 8GB of executor memory

**Comment by balbarka** [comment]
I'm aligned on the above pseudocode. I still think we'll eventually need
some type of directory checkpoint logic, but not for an MVP.
